name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call_build_and_push:
    uses: ./.github/workflows/build_and_push.yml
    with:
      service_name: 'nike_shopping'
      dockerfile_path: 'Dockerfile'
      context_path: './'
    secrets: 
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}